apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"  
stringData:
  datasources.yaml: |- 
    datasources:
      - name: "Loki"
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
        editable: false
      - name: "Victoria-Metrics"
        type: prometheus
        access: proxy
        url: http://vmetrics-victoria-metrics-single-server:8428
        isDefault: true
        editable: true