kind: Service
apiVersion: v1
metadata:
  name:  grafana-port
  namespace: monitoring
spec:
  type:  NodePort 
  selector:    
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  ports:
  - protocol: TCP
    nodePort: 30999
    port:  80
    targetPort: 3000