prometheus:  
  prometheusSpec:
    remoteWrite:
       - url: http://vmetrics-victoria-metrics-single-server:8428/api/v1/write
grafana:
  adminPassword: xxxxx
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: false
  grafana.ini:
    server:
      root_url: http://10.129.134.153/grafana #Ip Address must be fullfil with varriables
