apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: pv-loki
  labels:
    type: local
spec:
  storageClassName: loki-storageclass
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/loki"