apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: pv-victoria-metrics
  labels:
    type: local
spec:
  storageClassName: victoria-metrics-storageclass
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/victoria-metrics"