apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplerestapi
  namespace: simplerestapi
  labels:
    app: my-first-app
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: simplerestapi
  template:
    metadata:
      labels:
        app: simplerestapi
    spec:
      serviceAccountName: serviceaccountforapi
      containers:
      - name: simple-rest-api
        image: k8s/simplerestapi:v4.4.0
        imagePullPolicy: Never
        env:
          - name: KEY-1
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: key-1
          - name: KEY-2
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: key-2  
        resources: 
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 125Mi
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name : config-volume
        configMap:
         name: example-config