kind: Service
apiVersion: v1
metadata:
  name:  simplerestapi
  namespace: simplerestapi
spec:
  type:  NodePort 
  selector:
    app:  simplerestapi  
  ports:
  - protocol: TCP
    nodePort: 30001
    port:  8080
    targetPort:  8080