kind: Service
apiVersion: v1
metadata:
  name:  simplerestapi
  namespace: simplerestapi
spec:
  type:  ClusterIP 
  selector:
    app:  simplerestapi  
  ports:
  - protocol: TCP
    port:  8080
    targetPort:  8080